# Generated by Django 5.2.7 on 2025-10-22 13:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя файла')),
                ('file_sha256', models.CharField(max_length=64, verbose_name='SHA256')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Всего строк')),
                ('inserted', models.PositiveIntegerField(default=0, verbose_name='Вставлено')),
                ('duplicates_in_file', models.PositiveIntegerField(default=0, verbose_name='Дубли в файле')),
                ('duplicates_in_db', models.PositiveIntegerField(default=0, verbose_name='Дубли в БД')),
                ('invalid_rows', models.PositiveIntegerField(default=0, verbose_name='Некорректных строк')),
                ('duration_sec', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8, verbose_name='Длительность, с')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='Ошибки')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='inventory.batch', verbose_name='Партия')),
            ],
            options={
                'verbose_name': 'Импорт',
                'verbose_name_plural': 'Импорты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['batch'], name='audit_impor_batch_i_e8fcde_idx'), models.Index(fields=['file_sha256'], name='audit_impor_file_sh_fbce61_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'file_sha256'), name='uq_importlog_batch_sha256'), models.CheckConstraint(condition=models.Q(('duration_sec__gte', 0)), name='ck_importlog_duration_nonneg')],
            },
        ),
    ]
