# Generated by Django 5.2.7 on 2025-10-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='importlog',
            name='uq_importlog_batch_sha256',
        ),
    ]
