# Generated by Django 5.2.7 on 2025-10-22 13:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('number', models.CharField(max_length=64, unique=True, verbose_name='Номер партии')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
            },
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('number_in_batch', models.PositiveIntegerField(verbose_name='Номер в партии')),
                ('length_m', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('1000000.00'))], verbose_name='Длина по партии, м')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.batch')),
                ('drum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_items', to='catalog.drum')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='storage.storage')),
            ],
            options={
                'verbose_name': 'Предмет в партии',
                'verbose_name_plural': 'Предметы в партии',
                'indexes': [models.Index(fields=['batch'], name='inventory_b_batch_i_8103a3_idx'), models.Index(fields=['drum'], name='inventory_b_drum_id_db6ce1_idx'), models.Index(fields=['storage_location'], name='inventory_b_storage_5d69d6_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'number_in_batch'), name='uq_batch_number_in_batch'), models.CheckConstraint(condition=models.Q(('length_m__gt', 0)), name='ck_batchitem_length_pos'), models.CheckConstraint(condition=models.Q(('number_in_batch__gt', 0)), name='ck_batchitem_number_in_batch_pos')],
            },
        ),
    ]
