# Generated by Django 5.2.7 on 2025-10-22 12:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код модели')),
                ('name', models.CharField(blank=True, default='', max_length=128, verbose_name='Название')),
                ('min_length_m', models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Мин. длина, м')),
                ('max_length_m', models.DecimalField(decimal_places=2, default=Decimal('1000000.00'), max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('1000000.00'))], verbose_name='Макс. длина, м')),
            ],
            options={
                'verbose_name': 'Модель кабеля',
                'verbose_name_plural': 'Модели кабеля',
                'constraints': [models.CheckConstraint(condition=models.Q(('min_length_m__gt', 0)), name='ck_cablemodel_min_pos'), models.CheckConstraint(condition=models.Q(('max_length_m__gt', 0)), name='ck_cablemodel_max_pos'), models.CheckConstraint(condition=models.Q(('max_length_m__gte', models.F('min_length_m'))), name='ck_cablemodel_bounds')],
            },
        ),
        migrations.CreateModel(
            name='Drum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код барабана')),
                ('initial_length_m', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('1000000.00'))], verbose_name='Первичная длина, м')),
                ('cable_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drums', to='catalog.cablemodel', verbose_name='Модель кабеля')),
            ],
            options={
                'verbose_name': 'Барабан',
                'verbose_name_plural': 'Барабаны',
                'constraints': [models.CheckConstraint(condition=models.Q(('initial_length_m__gt', 0)), name='ck_drum_initial_pos')],
            },
        ),
    ]
